/**
 * models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 0 - AGENT  1 - ADMIN 
 */
export type RequestedByUserType = 'AGENT' | 'ADMIN';

export const RequestedByUserType = {
    Agent: 'AGENT' as RequestedByUserType,
    Admin: 'ADMIN' as RequestedByUserType
};

