/**
 * models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Polyline } from './polyline';
import { RequestedBy } from './requestedBy';


export interface SavedPolylineEvent { 
    polyline: Polyline;
    requestedBy: RequestedBy;
}

